openapi: 3.0.0

info:
  title: TüåçSI BüåéSI URL API 
  description: |
    API —Å–æ—Ü–∏–∞–ª—å–Ω–æ–∏ÃÜ —Å–µ—Ç–∏ –ø—É—Ç–µ—à–µ—Å—Ç–≤–µ–Ω–Ω–∏–∫–æ–≤ "Tosi bosi" –¥–ª—è –∫—É—Ä—Å–∞ –ø–æ System Design Balun.Course
    
  
    - –¢–æ–∫–µ–Ω –ø–µ—Ä–µ–¥–∞–µ—Ç—Å—è –ø–æ email –æ—Ç–≤–µ—Ç—Å—Ç–≤–µ–Ω–Ω–æ–º—É –ª–∏—Ü—É –≤ –æ–¥–Ω–æ—Ä–∞–∑–æ–≤—ã—Ö –∑–∞–ø–∏—Å–∫–∞—Ö privnote.com. 
    - –£—Ä–æ–≤–µ–Ω—å –∑–∞—â–∏—Ç—ã –Ω–∏–∑–∫–∏–π. –í –±—É–¥—É—â–µ–º –ø–∞–Ω–∏—Ä—É–µ—Ç—Å—è —Ä–µ–∞–ª–∏–∑–æ–≤–∞—Ç—å –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏—é –ø–æ –ø—Ä–æ—Ç–æ–∫–æ–ª—É OAuth 2.0
  contact:
    name: –ö—É—Ä—Å –ø–æ System Design Balun.Cours
    url: https://balun.courses/courses/system_design#program
    
  version: 1.0.0
tags:
  - name: –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ—Å—Ç–∞–º–∏ 
  - name: –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è–º–∏
  - name: –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –æ—Ü–µ–Ω–∫–∞–º–∏
  - name: –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ–¥–ø–∏—Å–∫–∞–º–∏/–æ—Ç–ø–∏—Å–∫–∞–º–∏

paths:
  '/v1/post':
    post:
      summary: –°–æ–∑–¥–∞–Ω–∏–µ –æ–¥–Ω–æ–≥–æ –ø–æ—Å—Ç–∞
      operationId: –°reatePost
      description:  |
        –ú–µ—Ç–æ–¥ —Å–æ–∑–¥–∞–µ—Ç `–æ–¥–∏–Ω` –ø–æ—Å—Ç –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è.
        
        –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –º–æ–∂–µ—Ç –ø—É–±–ª–∏–∫–æ–≤–∞—Ç—å –Ω–µ –±–æ–ª–µ–µ `20` —Å–≤–æ–∏—Ö –ø–æ—Å—Ç–æ–≤ –≤ –¥–µ–Ω—å. 
        
        –û–ø–∏—Å–∞–Ω–∏–µ –Ω–µ –¥–æ–ª–∂–Ω–æ –ø—Ä–µ–≤—ã—à–∞—Ç—å `250` —Å–∏–º–≤–æ–ª–æ–≤     
      tags:
        - –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ—Å—Ç–∞–º–∏
      requestBody:
        required: true
        content:
          application/json:
            schema:
      
              type: object
              'properties':
                author_user_id:
                  type: string
                  format: UUID
                  description: id –∞–≤—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID)
                title:
                  type: string
                  description: –ù–∞–∑–≤–∞–Ω–∏–µ –ø–æ—Å—Ç–∞ (–∑–∞–≥–æ–ª–æ–≤–æ–∫). –ú–∞–∫—Å–∏–º—É–º `100` —Å–∏–º–≤–æ–ª–æ–≤  
                comment:
                  type: string
                  description: –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π/–æ–ø–∏—Å–∞–Ω–∏–µ –∫ –ø–æ—Å—Ç—É. –û–ø–∏—Å–∞–Ω–∏–µ –Ω–µ –¥–æ–ª–∂–Ω–æ –ø—Ä–µ–≤—ã—à–∞—Ç—å `250` —Å–∏–º–≤–æ–ª–æ–≤.
                city:
                    type: string
                    description: –ó–Ω–∞—á–µ–Ω–∏–µ –≥–æ—Ä–æ–¥–∞ –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "city"
                    enum:
                        - –õ–∞—Ö–¥–µ–Ω–ø–æ—Ö—å—è
                        - –ú–æ—Å–∫–≤–∞
                        - –ú–∏–Ω—Å–∫
                        - –°–∞–º–∞—Ä–∞
                        - –ê—Å—Ç–∞–Ω–∞
                country:
                    type: string
                    description: –ó–Ω–∞—á–µ–Ω–∏–µ –≥–æ—Ä–æ–¥–∞ –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "country"
                    enum:
                        - –†–æ—Å—Å–∏—è
                        - –ö–∞–∑–∞—Ö—Å—Ç–∞–Ω
                        - –ö–∏—Ä–≥–∏–∑–∏—è
                        - –¢–∞–¥–∂–∏–∫–∏—Å—Ç–∞–Ω
                        - –ë–µ–ª–∞—Ä—É—Å—å
                hashtag:
                  type: array
                  items:
                    type: string
                    description: –°–ø–∏—Å–æ–∫ —Ö–µ—à—Ç–µ–≥–æ–≤
                created_at:  
                  type: string
                  format: date-time
                  description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –ø–æ—Å—Ç–∞
              
              required:
                - author_user_id
                - title
                - comment
                - city
                - country
                - created_at
               
            'examples':
              request:
                value:
                  author_user_id: "b6f641de-0067-4c74-a78a-8b03171aeaca"
                  title: "–ü–µ—Ä–≤—ã–π –¥–µ–Ω—å –≤ –ö–∞—Ä–µ–ª–∏–∏"
                  comment: "–ü–æ—Å–µ—Ç–∏–ª –≥–æ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤ –í–æ—Ç—Ç–æ–≤–∞–∞—Ä–∞. –ü–æ–¥—ä—ë–º –Ω–∞ —Å–≤—è—â–µ–Ω–Ω—É—é —Å–∞–∞–º—Å–∫—É—é –≥–æ—Ä—É —Ç—Ä–µ–±—É–µ—Ç —Ö–æ—Ä–æ—à–µ–π —Ñ–∏–∑–∏—á–µ—Å–∫–æ–π –ø–æ–¥–≥–æ—Ç–æ–≤–∫–∏, –Ω–æ –æ—Ç–∫—Ä—ã–≤–∞—é—â–∏–µ—Å—è –≤–∏–¥—ã –∫–æ–º–ø–µ–Ω—Å–∏—Ä—É—é—Ç —É—Å–∏–ª–∏—è"
                  city: "–õ–∞—Ö–¥–µ–Ω–ø–æ—Ö—å—è"
                  country_id: "–†–æ—Å—Å–∏—è"
                  hashtag: ["#–ö–∞—Ä–µ–ª–∏—è", "#–í–æ—Ç—Ç–æ–≤–∞–∞—Ä–∞"]
                  created_at: "2024-05-21T13:09:12Z"
                  
      'responses':
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: string
                    format: UUID
                    description: id —Å–æ–∑–¥–∞–Ω–Ω–æ–≥–æ –ø–æ—Å—Ç–∞ (UUID)
                required:
                  - post_id
              examples:
                response:
                  value:
                    post_id: "6b179778-439d-4415-ba1c-fdd114c3c38a"
        '404':
          description: –ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "author_user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ü—Ä–µ–≤—ã—à–µ–Ω –ª–∏–º–∏—Ç –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è 250 —Å–∏–º–≤–æ–ª–æ–≤"
                    parametr: "comment"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞"
                  
                   
  '/v1/upload/photos':
     post:
      summary: –ó–∞–≥—Ä—É–∑–∫–∞ —Ñ–æ—Ç–æ–≥—Ä–∞—Ñ–∏–π –≤ –ø–æ—Å—Ç –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è
      operationId: UploadPhotos
      description:  |
        –ú–µ—Ç–æ–¥ –∑–∞–≥—Ä—É–∂–∞–µ—Ç –¥–æ `6` —Ñ–æ—Ç–æ –≤ `–æ–¥–∏–Ω` –ø–æ—Å—Ç –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è.
        
        –ú–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–º —Ä–∞–∑–º–µ—Ä–æ–º –æ–¥–Ω–æ–π —Ñ–æ—Ç–æ–≥—Ä–∞—Ñ–∏–∏ `500–ö–±` 
        
      tags:
        - –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ—Å—Ç–∞–º–∏
      requestBody:
        required: true
        content:
          application/json:
            schema:
      
              type: object
              'properties':
                author_user_id:
                  type: string
                  format: UUID
                  description: id –∞–≤—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID)
                post_id:
                    type: string
                    format: UUID
                    description: id –ø–æ—Å—Ç–∞, –≤ –∫–æ—Ç–æ—Ä—ã–π –∑–∞–≥—Ä—É–∂–∞—é—Ç—Å—è —Ñ–æ—Ç–æ (UUID)
                link_1_photo:
                    type: string
                    description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
                link_2_photo:
                    type: string
                    description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
                link_3_photo:
                    type: string
                    description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
                link_4_photo:
                    type: string
                    description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
                link_5_photo:
                    type: string
                    description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
                link_6_photo:
                    type: string
                    description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
                created_at:  
                  type: string
                  format: date-time
                  description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è –∑–∞–≥—Ä—É–∑–∫–∏ —Ñ–æ—Ç–æ
                  
              required:
                - author_user_id
                - post_id
                - link_1_photo
                - created_at
               
            'examples':
              request:
                value:
                  author_user_id: "b6f641de-0067-4c74-a78a-8b03171aeaca"
                  post_id: "6b179778-439d-4415-ba1c-fdd114c3c38a"
                  link_1_photo: "https://tosi-bosi-bucket.s3c2.001.cloud.ru"
                  link_2_photo: "https://tosi-bosi-bucket.s3c2.002.cloud.ru"
                  link_3_photo: "https://tosi-bosi-bucket.s3c2.003.cloud.ru"
                  link_4_photo: "https://tosi-bosi-bucket.s3c2.004.cloud.ru"
                  link_5_photo: "https://tosi-bosi-bucket.s3c2.005.cloud.ru"
                  link_6_photo: "https://tosi-bosi-bucket.s3c2.006.cloud.ru"
                  created_at: "2024-05-23T11:19:11Z"
                  
      'responses':
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: string
                    format: UUID
                    description: id –ø–æ—Å—Ç–∞, –≤ –∫–æ—Ç–æ—Ä—ã–π –±—ã–ª–∏ –∑–∞–≥—Ä—É–∂–µ–Ω—ã —Ñ–æ—Ç–æ (UUID)
                required:
                  - post_id
              examples:
                response:
                  value:
                    post_id: "6b179778-439d-4415-ba1c-fdd114c3c38a"
        '404':
          description: –ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "author_user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ü—Ä–µ–≤—ã—à–µ–Ω –ª–∏–º–∏—Ç —Ä–∞–∑–º–µ—Ä–∞ —Ñ–æ—Ç–æ 500–ö–±"
                    parametr: "comment"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞"


  '/v1/posts':
    get:
      operationId: ListPosts
      description:  |
        –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –º–æ–∂–µ—Ç –ø—Ä–æ—Å–º–∞—Ç—Ä–∏–≤–∞—Ç—å –Ω–µ –±–æ–ª–µ–µ `2000` –ø–æ—Å—Ç–æ–≤ –≤ –¥–µ–Ω—å
        
      tags:
        - –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ—Å—Ç–∞–º–∏
      summary: –í–æ–∑–≤—Ä–∞—â–∞–µ—Ç —Å–ø–∏—Å–æ–∫ –ø–æ—Å—Ç–æ–≤ –ø–æ –∑–∞–¥–∞–Ω–Ω—ã–º —Ñ–∏–ª—å—Ç—Ä–∞–º.
      parameters:
        - name: author_user_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –ø–æ—Å—Ç–æ–≤ –ø–æ id –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π
          required: false
          schema:
            type: string
            format: uuid
          example: b6f641de-0067-4c74-a78a-8b03171aeaca
          
        - name: post_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –ø–æ—Å—Ç–æ–≤ –ø–æ id –ø–æ—Å—Ç–æ–≤
          required: false
          schema:
            type: string
            format: uuid
          example: 712d9b72-cd1a-42f0-bb7f-e319cde98849

        - name: country
          in: query
          description: –ü–µ—Ä–µ—á–µ–Ω—å –∑–∞–ø—Ä–∞—à–∏–≤–∞–µ–º—ã—Ö —Å—Ç—Ä–∞–Ω –¥–ª—è —Ñ–∏–ª—å—Ç—Ä–∞—Ü–∏–∏ –ø–æ—Å—Ç–æ–≤
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
                - –†–æ—Å—Å–∏—è
                - –ö–∞–∑–∞—Ö—Å—Ç–∞–Ω
                - –ö–∏—Ä–≥–∏–∑–∏—è
                - –¢–∞–¥–∂–∏–∫–∏—Å—Ç–∞–Ω
                - –ë–µ–ª–∞—Ä—É—Å—å
         
        - name: city
          in: query
          description: –ü–µ—Ä–µ—á–µ–Ω—å –∑–∞–ø—Ä–∞—à–∏–≤–∞–µ–º—ã—Ö –≥–æ—Ä–æ–¥–æ–≤ –¥–ª—è —Ñ–∏–ª—å—Ç—Ä–∞—Ü–∏–∏ –ø–æ—Å—Ç–æ–≤
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
                 - –õ–∞—Ö–¥–µ–Ω–ø–æ—Ö—å—è
                 - –ú–æ—Å–∫–≤–∞
                 - –ú–∏–Ω—Å–∫
                 - –°–∞–º–∞—Ä–∞
                 - –ê—Å—Ç–∞–Ω–∞
            
        - name: limit
          in: query
          description: –ú–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∑–∞–ø–∏—Å–µ–π, –∫–æ—Ç–æ—Ä–æ–µ –Ω—É–∂–Ω–æ –ø–æ–ª—É—á–∏—Ç—å –≤ –æ—Ç–≤–µ—Ç–µ
          required: true
          schema:
            type: integer
            default: 10
            example: 100
          
        - name: page
          in: query
          description: –ù–æ–º–µ—Ä —Å—Ç—Ä–∞–Ω–∏—Ü—ã –ø–∞–≥–∏–Ω–∞—Ü–∏–∏. –û–ø—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–π –ø–∞—Ä–∞–º–µ—Ç—Ä. –ü–æ —É–º–æ–ª—á–∞–Ω–∏—é 1.
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
        
      
      'responses':
        '200':
          description: –°–ø–∏—Å–æ–∫ –ø–æ—Å—Ç–æ–≤ —É—Å–ø–µ—à–Ω–æ –ø–æ–ª—É—á–µ–Ω
          content:
            application/json:
              schema:
                   $ref: '#/components/schemas/GetPostsView'
              
        '404':
          description: –ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "author_user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–π id –ø–æ—Å—Ç–∞ –≤ –∑–∞–ø—Ä–æ—Å–µ "
                    parametr: "post_id"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞"
  
  
  
  
  '/v1/comment':
    post:
      summary: –°–æ–∑–¥–∞–Ω–∏–µ –æ–¥–Ω–æ–≥–æ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è –∫ –ø–æ—Å—Ç—É
      operationId: CreateComment
      description:  |
        –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –º–æ–∂–µ—Ç –ø–∏—Å–∞—Ç—å –Ω–µ –±–æ–ª–µ–µ `500` –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –≤ –¥–µ–Ω—å –∫ –¥—Ä—É–≥–∏–º –ø–æ—Å—Ç–∞–º 
        
        –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π –Ω–µ –¥–æ–ª–∂–µ–Ω –ø—Ä–µ–≤—ã—à–∞—Ç—å `500` —Å–∏–º–≤–æ–ª–æ–≤
      tags:
        -  –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è–º–∏
      requestBody:
        required: true
        content:
          application/json:
            schema:
      
              type: object
              'properties':
                author_user_id:
                  type: string
                  format: UUID
                  description: id –∞–≤—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID)
                post_id:
                  type: string
                  format: UUID
                  description: id –ø–æ—Å—Ç–∞ (UUID)   
                commentator_user_id:
                  type: string
                  format: UUID
                  description: id –∫–æ–º–º–µ–Ω—Ç–æ—Ç–∞—Ä–æ –ø–æ—Å—Ç–∞ (UUID) 
                comment:
                  type: string
                  description: –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π –∫ –ø–æ—Å—Ç—É. –û–ø–∏—Å–∞–Ω–∏–µ –Ω–µ –¥–æ–ª–∂–Ω–æ –ø—Ä–µ–≤—ã—à–∞—Ç—å `500` —Å–∏–º–≤–æ–ª–æ–≤.
                comment_status:
                    type: string
                    description: –ó–Ω–∞—á–µ–Ω–∏–µ —Å—Ç–∞—Ç—É—Å–∞ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "comment_statuses"
                    enum:
                        - new
                        - viewed
                created_at:  
                  type: string
                  format: date-time
                  description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è
                  
              required:
                - author_user_id
                - post_id
                - comment
                - commentator_user_id
                - comment_status
                - created_at
               
            'examples':
              request:
                value:
                  author_user_id: "b6f641de-0067-4c74-a78a-8b03171aeaca"
                  post_id: "1ceae90a-fb91-43c1-90a0-246638c2dbae"
                  commentator_user_id: "a3de7b75-185f-4912-a40c-19b8ae443c99"
                  comment: "–í–µ—Å—å–º–∞ –∞—Ç–º–æ—Å—Ñ–µ—Ä–Ω–æ. –í–∞—à–µ –ø—É—Ç–µ—à–µ—Å—Ç–≤–∏–µ –º–µ–Ω—è –≤–¥–æ—Ö–Ω–æ–≤–ª—è–µ—Ç"
                  status: "new"
                  created_at: "2024-05-21T13:09:12Z"
                  
      'responses':
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: string
                    format: UUID
                    description: id —Å–æ–∑–¥–∞–Ω–Ω–æ–≥–æ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è (UUID)
                required:
                  - comment_id
              examples:
                response:
                  value:
                    comment_id: "6b179778-439d-4415-ba1c-fdd114c3c38a"
        '404':
          description: –ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ü–æ—Å—Ç —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "post_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ü—Ä–µ–≤—ã—à–µ–Ω –ª–∏–º–∏—Ç –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è 500 —Å–∏–º–≤–æ–ª–æ–≤"
                    parametr: "comment"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞"
  
  
  '/v1/comments':
    get:
      operationId: ListComments
      description:  |
        –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –º–æ–∂–µ—Ç –ø—Ä–æ—Å–º–∞—Ç—Ä–∏–≤–∞—Ç—å –Ω–µ –±–æ–ª–µ–µ `2000` –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –¥—Ä—É–≥–∏—Ö –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –≤ –¥–µ–Ω—å
        
      tags:
        - –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è–º–∏
      summary: –í–æ–∑–≤—Ä–∞—â–∞–µ—Ç —Å–ø–∏—Å–æ–∫ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –ø–æ –∑–∞–¥–∞–Ω–Ω—ã–º —Ñ–∏–ª—å—Ç—Ä–∞–º.
      parameters:
        - name: author_user_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –ø–æ id –∞–≤—Ç–æ—Ä–æ–≤ –ø–æ—Å—Ç–∞
          required: false
          schema:
            type: string
            format: uuid
          example: b6f641de-0067-4c74-a78a-8b03171aeaca
          
        - name: post_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –ø–æ id –ø–æ—Å—Ç–æ–≤
          required: false
          schema:
            type: string
            format: uuid
          example: 712d9b72-cd1a-42f0-bb7f-e319cde98849
        
        - name: commentator_user_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –ø–æ id –∫–æ–º–º–µ–Ω—Ç–∞—Ç–æ—Ä–æ–≤ –ø–æ—Å—Ç–æ–≤
          required: false
          schema:
            type: string
            format: uuid
            example: 712d9b72-cd1a-42f0-bb7f-e319cde98849    
          
        - name: comment_status
          in: query
          description: –§–∏–ª—å—Ç—Ä–∞—Ü–∏—è –ø–æ —Å—Ç–∞—Ç—É—Å–∞–º –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
                - viewed
                - read
         
        - name: limit
          in: query
          description: –ú–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∑–∞–ø–∏—Å–µ–π, –∫–æ—Ç–æ—Ä–æ–µ –Ω—É–∂–Ω–æ –ø–æ–ª—É—á–∏—Ç—å –≤ –æ—Ç–≤–µ—Ç–µ
          required: true
          schema:
            type: integer
            default: 10
            example: 100
            
        - name: page
          in: query
          description: –ù–æ–º–µ—Ä —Å—Ç—Ä–∞–Ω–∏—Ü—ã –ø–∞–≥–∏–Ω–∞—Ü–∏–∏. –û–ø—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–π –ø–∞—Ä–∞–º–µ—Ç—Ä. –ü–æ —É–º–æ–ª—á–∞–Ω–∏—é 1.
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
        
      
      'responses':
        '200':
          description: –°–ø–∏—Å–æ–∫ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ —É—Å–ø–µ—à–Ω–æ –ø–æ–ª—É—á–µ–Ω
          content:
            application/json:
              schema:
                   $ref: '#/components/schemas/GetCommentsView'
              
        '404':
          description: –ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "author_user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–π id –ø–æ—Å—Ç–∞ –≤ –∑–∞–ø—Ä–æ—Å–µ "
                    parametr: "post_id"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞"
  
  
  
  
  
  '/v1/rating':
    post:
      summary: –û—Ü–µ–Ω–∫–∞ –æ–¥–Ω–æ–≥–æ –ø–æ—Å—Ç–∞
      operationId: CreateRating
      description:  |
        –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –º–æ–∂–µ—Ç –æ—Ü–µ–Ω–∏–≤–∞—Ç—å –Ω–µ –±–æ–ª–µ–µ `500` –ø–æ—Å—Ç–æ–≤ –≤ –¥–µ–Ω—å
      tags:
        -  –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –æ—Ü–µ–Ω–∫–∞–º–∏
      requestBody:
        required: true
        content:
          application/json:
            schema:
      
              type: object
              'properties':
                author_user_id:
                  type: string
                  format: UUID
                  description: id –∞–≤—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID)
                post_id:
                  type: string
                  format: UUID
                  description: id –ø–æ—Å—Ç–∞ (UUID)   
                commentator_user_id:
                  type: string
                  format: UUID
                  description: id –∫–æ–º–º–µ–Ω—Ç–∞—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID) 
                rating:
                  type: integer
                  description: –û—Ü–µ–Ω–∫–∞ –ø–æ—Å—Ç–∞
                  minLength: 1
                  maxLength: 5
                rating_status:
                    type: string
                    description: –ó–Ω–∞—á–µ–Ω–∏–µ —Å—Ç–∞—Ç—É—Å–∞ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "rating_statuses"
                    enum:
                        - new
                        - viewed
                created_at:  
                  type: string
                  format: date-time
                  description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –æ—Ü–µ–Ω–∫–∏
                  
              required:
                - author_user_id
                - post_id
                - commentator_user_id
                - rating
                - rating_status
                - created_at
               
            'examples':
              request:
                value:
                  author_user_id: "b6f641de-0067-4c74-a78a-8b03171aeaca"
                  post_id: "1ceae90a-fb91-43c1-90a0-246638c2dbae"
                  commentator_user_id: "a3de7b75-185f-4912-a40c-19b8ae443c99"
                  rating: 5
                  rating_status: "new"
                  created_at: "2024-05-21T13:09:12Z"
                  
      'responses':
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  rating_id:
                    type: string
                    format: UUID
                    description: id —Å–æ–∑–¥–∞–Ω–Ω–æ–π –æ—Ü–µ–Ω–∫–∏ (UUID)
                required:
                  - rating_id
              examples:
                response:
                  value:
                    rating_id: "6b179778-439d-4415-ba1c-fdd114c3c38a"
        '404':
          description: –ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "author_user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ü—Ä–µ–≤—ã—à–µ–Ω –ª–∏–º–∏—Ç –æ—Ü–µ–Ω–∫–∏ –ø–æ—Å—Ç–æ–≤ 500"
                    parametr: "rating"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞" 
  
  
  '/v1/ratings':
    get:
      operationId: ListRatings
      description:  |
      tags:
        - –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –æ—Ü–µ–Ω–∫–∞–º–∏
      summary: –í–æ–∑–≤—Ä–∞—â–∞–µ—Ç —Å–ø–∏—Å–æ–∫ –æ—Ü–µ–Ω–æ–∫ –ø–æ –∑–∞–¥–∞–Ω–Ω—ã–º —Ñ–∏–ª—å—Ç—Ä–∞–º.
      parameters:
        - name: author_user_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –æ—Ü–µ–Ω–æ–∫ –ø–æ id –∞–≤—Ç–æ—Ä–æ–≤ –ø–æ—Å—Ç–∞
          required: false
          schema:
            type: string
            format: uuid
          example: b6f641de-0067-4c74-a78a-8b03171aeaca
          
        - name: post_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –æ—Ü–µ–Ω–æ–∫ –ø–æ id –ø–æ—Å—Ç–æ–≤
          required: false
          schema:
            type: string
            format: uuid
          example: 712d9b72-cd1a-42f0-bb7f-e319cde98849
        
        - name: commentator_user_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –æ—Ü–µ–Ω–æ–∫ –ø–æ id –∫–æ–º–º–µ–Ω—Ç–∞—Ç–æ—Ä–æ–≤ –ø–æ—Å—Ç–æ–≤
          required: false
          schema:
            type: string
            format: uuid
            example: 712d9b72-cd1a-42f0-bb7f-e319cde98849    
          
        - name: ratingt
          in: query
          description: –§–∏–ª—å—Ç—Ä–∞—Ü–∏—è –ø–æ—Å—Ç–æ–≤ –ø–æ –æ—Ü–µ–Ω–∫–µ
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
              enum:
                - 1
                - 2
                - 3
                - 4
                - 5
          
        - name: ratingt_status
          in: query
          description: –§–∏–ª—å—Ç—Ä–∞—Ü–∏—è –ø–æ —Å—Ç–∞—Ç—É—Å–∞–º –æ—Ü–µ–Ω–æ–∫
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
                - viewed
                - read
                
        - name: limit
          in: query
          description: –ú–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∑–∞–ø–∏—Å–µ–π, –∫–æ—Ç–æ—Ä–æ–µ –Ω—É–∂–Ω–æ –ø–æ–ª—É—á–∏—Ç—å –≤ –æ—Ç–≤–µ—Ç–µ
          required: true
          schema:
            type: integer
            default: 10
            example: 100
            
        - name: page
          in: query
          description: –ù–æ–º–µ—Ä —Å—Ç—Ä–∞–Ω–∏—Ü—ã –ø–∞–≥–∏–Ω–∞—Ü–∏–∏. –û–ø—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–π –ø–∞—Ä–∞–º–µ—Ç—Ä. –ü–æ —É–º–æ–ª—á–∞–Ω–∏—é 1.
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
        
      
      'responses':
        '200':
          description: –°–ø–∏—Å–æ–∫ –æ—Ü–µ–Ω–æ–∫ —É—Å–ø–µ—à–Ω–æ –ø–æ–ª—É—á–µ–Ω
          content:
            application/json:
              schema:
                   $ref: '#/components/schemas/GetRatingsView'
              
        '404':
          description: –ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ê–≤—Ç–æ—Ä —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "author_user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–π id –ø–æ—Å—Ç–∞ –≤ –∑–∞–ø—Ä–æ—Å–µ "
                    parametr: "post_id"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞"
  
  
  
  
  
  '/v1/subscription':
    post:
      summary: –ü–æ–¥–ø–∏—Å–∫–∞ –Ω–∞ –æ–¥–Ω–æ–≥–æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è
      operationId: CreateSubscribtion
      description:  |
        –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –º–æ–∂–µ—Ç –ø–æ–¥–ø–∏—Å—ã–≤–∞—Ç—å –Ω–µ –±–æ–ª–µ–µ —á–µ–º –Ω–∞ `500` –¥—Ä—É–≥–∏—Ö –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –≤ –¥–µ–Ω—å
        
      tags:
        -  –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ–¥–ø–∏—Å–∫–∞–º–∏/–æ—Ç–ø–∏—Å–∫–∞–º–∏
      requestBody:
        required: true
        content:
          application/json:
            schema:
      
              type: object
              'properties':
                user_id:
                  type: string
                  format: UUID
                  description: id –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è, –Ω–∞ –∫–æ—Ç–æ—Ä–æ–≥–æ –ø–æ–¥–ø–∏—Å—ã–≤–∞—é—Ç—Å—è (UUID)
                subscriber_user_id:
                  type: string
                  format: UUID
                  description: id –ø–æ–¥–ø–∏—Å—á–∏–∫–∞, –∫–æ—Ç–æ—Ä—ã–π –ø–æ–¥–ø–∏—Å—ã–≤–∞–µ—Ç—Å—è –Ω–∞ –¥—Ä—É–≥–æ–≥–æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è (UUID) 
                is_subscription:
                  type: boolean
                  description: true - –ø–æ–¥–ø–∏—Å–∫–∞ false - –æ—Ç–ø–∏—Å–∫–∞
                created_at:  
                  type: string
                  format: date-time
                  description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –ø–æ–¥–ø–∏—Å–∫–∏/–æ—Ç–ø–∏—Å–∫–∏
                  
              required:
                - user_id
                - subscriber_user_id
                - is_subscription
                - created_at
               
            'examples':
              request:
                value:
                  user_id: "b6f641de-0067-4c74-a78a-8b03171aeaca"
                  subscriber_user_id: "1ceae90a-fb91-43c1-90a0-246638c2dbae"
                  is_subscription: true
                  created_at: "2024-05-21T13:09:12Z"
                  
      'responses':
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscription_id:
                    type: string
                    format: UUID
                    description: id —Å–æ–∑–¥–∞–Ω–Ω–æ–π –ø–æ–¥–ø–∏—Å–∫–∏/–æ—Ç–ø–∏—Å–∫–∏ (UUID)
                required:
                  - rating_id
              examples:
                response:
                  value:
                   subscription_id: "6b179778-439d-4415-ba1c-fdd114c3c38a"
        '404':
          description: –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  
              examples:
                response:
                  value:
                    message: "–ü—Ä–µ–≤—ã—à–µ–Ω –ª–∏–º–∏—Ç –ø–æ–¥–ø–∏—Å–∫–∏ –Ω–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π 500"
                   
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞" 
  
  
  '/v1/subscriptions':
    get:
      operationId: ListSubscriptions
      description:  |
      tags:
        - –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ–¥–ø–∏—Å–∫–∞–º–∏/–æ—Ç–ø–∏—Å–∫–∞–º–∏
      summary: –í–æ–∑–≤—Ä–∞—â–∞–µ—Ç —Å–ø–∏—Å–æ–∫ –ø–æ–¥–ø–∏—Å–æ–∫ –ø–æ –∑–∞–¥–∞–Ω–Ω—ã–º —Ñ–∏–ª—å—Ç—Ä–∞–º
      parameters:
        - name: user_id
          in: query
          description: –§–∏–ª—å—Ç—Ä –¥–ª—è –ø–æ–∏—Å–∫–∞ –≤—Å–µ—Ö –ø–æ–¥–ø–∏—Å–æ–∫ –Ω–∞ –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω–æ–≥–æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è
          required: false
          schema:
            type: string
            format: uuid
            example: b6f641de-0067-4c74-a78a-8b03171aeaca
          
        - name: is_subscription
          in: query
          description: –§–∏–ª—å—Ç—Ä–∞—Ü–∏—è –ø–æ–¥–ø–∏—Å–æ–∫ –ø–æ —Å—Ç–∞—Ç—É—Å–∞–º –ø–æ–¥–ø–∏—Å–∫–∞/–æ—Ç–ø–∏—Å–∫–∞
          style: form
          explode: false
          schema:
            type: boolean
            items:
              type: string
              enum:
                - true
                - false
                
        - name: limit
          in: query
          description: –ú–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∑–∞–ø–∏—Å–µ–π, –∫–æ—Ç–æ—Ä–æ–µ –Ω—É–∂–Ω–æ –ø–æ–ª—É—á–∏—Ç—å –≤ –æ—Ç–≤–µ—Ç–µ
          required: true
          schema:
            type: integer
            default: 10
            example: 100
            
        - name: page
          in: query
          description: –ù–æ–º–µ—Ä —Å—Ç—Ä–∞–Ω–∏—Ü—ã –ø–∞–≥–∏–Ω–∞—Ü–∏–∏. –û–ø—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–π –ø–∞—Ä–∞–º–µ—Ç—Ä. –ü–æ —É–º–æ–ª—á–∞–Ω–∏—é 1.
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
        
      
      'responses':
        '200':
          description: –°–ø–∏—Å–æ–∫ –ø–æ–¥–ø–∏—Å–æ–∫/–æ—Ç–ø–∏—Å–æ–∫ —É—Å–ø–µ—à–Ω–æ –ø–æ–ª—É—á–µ–Ω
          content:
            application/json:
              schema:
                   $ref: '#/components/schemas/GetSubscriptionView'
              
        '404':
          description: –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º –Ω–µ –Ω–∞–π–¥–µ–Ω"
                    parametr: "user_id"
        '400':
          description: –ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                  parameter:
                    type: string
                    description: –ü–∞—Ä–∞–º–µ—Ç—Ä –≤—ã–∑–≤–∞–≤—à–∏–π –æ—à–∏–±–∫—É
                required:
                  - message
                  - parameter
              examples:
                response:
                  value:
                    message: "–ù–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–π id –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –≤ –∑–∞–ø—Ä–æ—Å–µ "
                    parametr: "user_id"
        '500':
          description: –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏
                required:
                  - message

              examples:
                response:
                  value:
                    message: "–í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞"  
  
  
  
'components':
  schemas:
    'Posts':
      description: –°–ø–∏—Å–æ–∫ –ø–æ—Å—Ç–æ–≤ —Å–æ–≥–ª–∞—Å–Ω–æ –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º –∑–∞–ø—Ä–æ—Å–∞
      required:
        - author_user_id
        - post_id
        - title
        - comment
        - city
        - country
        - created_at
      type: object
      properties:
        author_user_id:
          type: string
          format: UUID
          description: id –∞–≤—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID)
          example: b6f641de-0067-4c74-a78a-8b03171aeaca
        post_id:
            type: string
            format: UUID
            description: id –ø–æ—Å—Ç–∞, –≤ –∫–æ—Ç–æ—Ä—ã–π –∑–∞–≥—Ä—É–∂–∞—é—Ç—Å—è —Ñ–æ—Ç–æ (UUID)
            example: 32104a52-5e97-49f3-a44f-49f8700ed5b8
        title:
          type: string
          description: –ù–∞–∑–≤–∞–Ω–∏–µ –ø–æ—Å—Ç–∞ (–∑–∞–≥–æ–ª–æ–≤–æ–∫). –ú–∞–∫—Å–∏–º—É–º `100` —Å–∏–º–≤–æ–ª–æ–≤  
          example: –ü–µ—Ä–≤—ã–π –¥–µ–Ω—å –≤ –ö–∞—Ä–µ–ª–∏–∏
        comment:
          type: string
          description: –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π/–æ–ø–∏—Å–∞–Ω–∏–µ –∫ –ø–æ—Å—Ç—É. –û–ø–∏—Å–∞–Ω–∏–µ –Ω–µ –¥–æ–ª–∂–Ω–æ –ø—Ä–µ–≤—ã—à–∞—Ç—å `250` —Å–∏–º–≤–æ–ª–æ–≤.
          example: –ü–æ—Å–µ—Ç–∏–ª –≥–æ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤ –í–æ—Ç—Ç–æ–≤–∞–∞—Ä–∞. –ü–æ–¥—ä—ë–º –Ω–∞ —Å–≤—è—â–µ–Ω–Ω—É—é —Å–∞–∞–º—Å–∫—É—é –≥–æ—Ä—É —Ç—Ä–µ–±—É–µ—Ç —Ö–æ—Ä–æ—à–µ–π —Ñ–∏–∑–∏—á–µ—Å–∫–æ–π –ø–æ–¥–≥–æ—Ç–æ–≤–∫–∏, –Ω–æ –æ—Ç–∫—Ä—ã–≤–∞—é—â–∏–µ—Å—è –≤–∏–¥—ã –∫–æ–º–ø–µ–Ω—Å–∏—Ä—É—é—Ç —É—Å–∏–ª–∏—è
        city:
          type: string
          description: –ó–Ω–∞—á–µ–Ω–∏–µ –≥–æ—Ä–æ–¥–∞ –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "city"
          enum:
              - –õ–∞—Ö–¥–µ–Ω–ø–æ—Ö—å—è
              - –ú–æ—Å–∫–≤–∞
              - –ú–∏–Ω—Å–∫
              - –°–∞–º–∞—Ä–∞
              - –ê—Å—Ç–∞–Ω–∞
        country:
          type: string
          description: –ó–Ω–∞—á–µ–Ω–∏–µ –≥–æ—Ä–æ–¥–∞ –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "country"
          enum:
              - –†–æ—Å—Å–∏—è
              - –ö–∞–∑–∞—Ö—Å—Ç–∞–Ω
              - –ö–∏—Ä–≥–∏–∑–∏—è
              - –¢–∞–¥–∂–∏–∫–∏—Å—Ç–∞–Ω
              - –ë–µ–ª–∞—Ä—É—Å—å
        hashtag:
            type: array
            items:
              type: string
              description: –°–ø–∏—Å–æ–∫ —Ö–µ—à—Ç–µ–≥–æ–≤
              example: '#–ö–∞—Ä–µ–ª–∏—è' 
        link_1_photo:
            type: string
            description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
            example: "https://tosi-bosi-bucket.s3c2.001.cloud.ru"
        link_2_photo:
            type: string
            description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
            example: "https://tosi-bosi-bucket.s3c2.002.cloud.ru"
        link_3_photo:
            type: string
            description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è 
            example: "https://tosi-bosi-bucket.s3c2.003.cloud.ru"
        link_4_photo:
            type: string
            description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è
            example: "https://tosi-bosi-bucket.s3c2.004.cloud.ru"
        link_5_photo:
            type: string
            description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è
            example: "https://tosi-bosi-bucket.s3c2.005.cloud.ru"
        link_6_photo:
            type: string
            description: URL –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è
            example: "https://tosi-bosi-bucket.s3c2.006.cloud.ru"
        created_at:  
              type: string
              format: date-time
              description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –ø–æ—Å—Ç–∞
              example: 2024-05-21T13:09:12Z
    'GetPostsView':
      required:
        - author_user_id
        - title
        - comment
        - city
        - country
        - created_a
      type: object
      properties:
        posts:
          type: array
          description: –°–ø–∏—Å–æ–∫ –ø–æ—Å—Ç–æ–≤
          items:
            $ref: '#/components/schemas/Posts'
  
 
 
    'Comments':
      description: –°–ø–∏—Å–æ–∫ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ —Å–æ–≥–ª–∞—Å–Ω–æ –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º –∑–∞–ø—Ä–æ—Å–∞
      required:
        - author_user_id
        - post_id
        - commentator_user_id
        - comment_status
        - status
        - created_at
      
      type: object
      properties:
        author_user_id:
          type: string
          format: UUID
          description: id –∞–≤—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID)
          example: b6f641de-0067-4c74-a78a-8b03171aeaca
        post_id:
            type: string
            format: UUID
            description: id –ø–æ—Å—Ç–∞ ()UUID)
            example: 32104a52-5e97-49f3-a44f-49f8700ed5b8
        commentator_user_id:
            type: string
            format: UUID
            description: id –ø–æ—Å—Ç–∞ ()UUID)
            example: 8ba8c124-d524-41ea-b967-24573c63104d
        comment:
          type: string
          description: –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π/–æ–ø–∏—Å–∞–Ω–∏–µ –∫ –ø–æ—Å—Ç—É. –û–ø–∏—Å–∞–Ω–∏–µ –Ω–µ –¥–æ–ª–∂–Ω–æ –ø—Ä–µ–≤—ã—à–∞—Ç—å `250` —Å–∏–º–≤–æ–ª–æ–≤.
          example: –í–µ—Å—å–º–∞ –∞—Ç–º–æ—Å—Ñ–µ—Ä–Ω–æ. –í–∞—à–µ –ø—É—Ç–µ—à–µ—Å—Ç–≤–∏–µ –º–µ–Ω—è –≤–¥–æ—Ö–Ω–æ–≤–ª—è–µ—Ç
        comment_status:
          type: string
          description: –ó–Ω–∞—á–µ–Ω–∏–µ —Å—Ç–∞—Ç—É—Å–∞ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "comment_statuses"
          enum:
            - new
            - viewed
        created_at:  
              type: string
              format: date-time
              description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è –∫ –ø–æ—Å—Ç—É
              example: 2024-05-21T13:09:12Z
    
    'GetCommentsView':
      required:
        - author_user_id
        - post_id
        - commentator_user_id
        - comment
        - comment_status
        - created_a
      type: object
      properties:
        comments:
          type: array
          description: –°–ø–∏—Å–æ–∫ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤
          items:
            $ref: '#/components/schemas/Comments'
 
 
 
    'Ritings':
      description: –°–ø–∏—Å–æ–∫ –æ—Ü–µ–Ω–æ–∫ —Å–æ–≥–ª–∞—Å–Ω–æ –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º –∑–∞–ø—Ä–æ—Å–∞
      required:
        - author_user_id
        - post_id
        - commentator_user_id
        - rating
        - rating_status
        - created_at
      
      type: object
      properties:
        author_user_id:
          type: string
          format: UUID
          description: id –∞–≤—Ç–æ—Ä–∞ –ø–æ—Å—Ç–∞ (UUID)
          example: b6f641de-0067-4c74-a78a-8b03171aeaca
        post_id:
            type: string
            format: UUID
            description: id –ø–æ—Å—Ç–∞ ()UUID)
            example: 32104a52-5e97-49f3-a44f-49f8700ed5b8
        commentator_user_id:
            type: string
            format: UUID
            description: id –ø–æ—Å—Ç–∞ ()UUID)
            example: 8ba8c124-d524-41ea-b967-24573c63104d
        rating:
            type: integer
            description: –û—Ü–µ–Ω–∫–∞ –ø–æ—Å—Ç–∞
            minLength: 1
            maxLength: 5
            example: 5
        rating_status:
            type: string
            description: –ó–Ω–∞—á–µ–Ω–∏–µ —Å—Ç–∞—Ç—É—Å–∞ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è –∏–∑ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ "rating_statuses"
            enum:
              - new
              - viewed
        
        created_at:  
              type: string
              format: date-time
              description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –æ—Ü–µ–Ω–∫–∏ –ø–æ—Å—Ç–∞
              example: 2024-05-21T13:09:12Z
    
    'GetRatingsView':
      required:
        - author_user_id
        - post_id
        - commentator_user_id
        - rating
        - rating_status
        - created_a
      type: object
      properties:
        ratings:
          type: array
          description: –°–ø–∏—Å–æ–∫ –æ—Ü–µ–Ω–æ–∫
          items:
            $ref: '#/components/schemas/Ritings'
 
 
 
    'Subscriptions':
      description: –°–ø–∏—Å–æ–∫ –ø–æ–¥–ø–∏—Å–æ–∫ —Å–æ–≥–ª–∞—Å–Ω–æ –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º –∑–∞–ø—Ä–æ—Å–∞
      required:
         - user_id
         - subscriber_user_id
         - is_subscription
         - created_at
      
      type: object
      properties:
        user_id:
            type: string
            format: UUID
            description: id –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è, –Ω–∞ –∫–æ—Ç–æ—Ä–æ–≥–æ –ø–æ–¥–ø–∏—Å—ã–≤–∞—é—Ç—Å—è (UUID)
        subscriber_user_id:
            type: string
            format: UUID
            description: id –ø–æ–¥–ø–∏—Å—á–∏–∫–∞, –∫–æ—Ç–æ—Ä—ã–π –ø–æ–¥–ø–∏—Å—ã–≤–∞–µ—Ç—Å—è –Ω–∞ –¥—Ä—É–≥–æ–≥–æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è (UUID) 
        is_subscription:
            type: boolean
            description: true - –ø–æ–¥–ø–∏—Å–∫–∞ false - –æ—Ç–ø–∏—Å–∫–∞
        created_at:  
            type: string
            format: date-time
            description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –ø–æ–¥–ø–∏—Å–∫–∏/–æ—Ç–ø–∏—Å–∫–∏
      
    'GetSubscriptionView':
      required:
         - user_id
         - subscriber_user_id
         - is_subscription
         - created_at
      type: object
      properties:
        subscriptions:
          type: array
          description: –°–ø–∏—Å–æ–∫ –ø–æ–¥–ø–∏—Å–æ–∫
          items:
            $ref: '#/components/schemas/Subscriptions'
  
 
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer 
      bearerFormat: JWT  # optional, for documentation purposes only
security:
  - bearerAuth: []  
   

 
 
 
 
 

          

          
          